name: bchfs-tests

on: [push, pull_request]

jobs:
  bchfs-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8']

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          git submodule update --init
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Install bcachefs-tools
        run: |
          sudo apt-get update
          sudo apt install gcc meson ninja-build
          sudo apt install make pkg-config libaio-dev libblkid-dev\
              libkeyutils-dev liblz4-dev libscrypt-dev libsodium-dev\
              liburcu-dev libzstd-dev libudev-dev uuid-dev zlib1g-dev\
              libfuse3-dev
          
          pip install git+https://github.com/Delaunay/bcachefs-pytools.git

      - name: Generate Link Image Data
        run: |
          truncate -s 10MiB testdata/link_image
          bcachefs format\
            --block_size=4k\
            --metadata_checksum=none\
            --data_checksum=none\
            --compression=none\
            --str_hash=siphash\
            --label=LabelDEADBEEF testdata/link_image
          mkdir dataset_mount
          bcachefs fusemount -s testdata/link_image dataset_mount

          echo "File contents" > dataset_mount/0.txt
          for i in {1..5000}; do ln "dataset_mount/0.txt" "dataset_mount/$i.txt"; done
          fusermount3 -u dataset_mount

      - name: Install
        run: |
          python setup.py -coverage develop

      - name: Tests
        run: | 
          coverage run --parallel-mode -m pytest tests/
          coverage combine
          coverage report -m
          coverage xml
          gcovr -r . -x -o .coverage_c.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: .coverage_c.xml,coverage.xml
