name: bchfs-tests

on: [push]

jobs:
  bchfs-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Requirements
        run: |
          git submodule update --init
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Install
        run: |
          python setup.py -coverage install

      - name: Tests
        run: |
          pytest tests
          bash <(curl -s https://codecov.io/bash)

