name: bchfs-tests

on: [push]

jobs:
  bchfs-clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: format
        run: |
          echo ""

  bchfs-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-9 g++-9
          sudo ln -f /usr/bin/gcov-9 /usr/bin/gcov
          pip install gcovr
          mkdir -p build

      - name: compile
        run: |
          git submodule update --init
          make coverage
          bash <(curl -s https://codecov.io/bash)


